spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        #主库
        master:
          minIdle: 5
          validationQuery: SELECT 1 FROM DUAL
          initialSize: 5
          maxWait: 60000
          filters: stat,wall,slf4j
          logSlowSql: true
          url: jdbc:mysql://127.0.0.1:3306/order?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
          username: root
          password: root
          testOnBorrow: false
          testWhileIdle: true
          minEvictableIdleTimeMillis: 300000
          timeBetweenEvictionRunsMillis: 60000
          testOnReturn: false
          maxActive: 20
          removeAbandoned: true
          removeAbandonedTimeout: 120
          logAbandoned: true
        #从库
        slave:
          minIdle: 5
          validationQuery: SELECT 1 FROM DUAL
          initialSize: 5
          maxWait: 60000
          filters: stat,wall,slf4j
          logSlowSql: true
          url: jdbc:mysql://127.0.0.1:3306/member?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
          username: root
          password: root
          testOnBorrow: false
          testWhileIdle: true
          minEvictableIdleTimeMillis: 300000
          timeBetweenEvictionRunsMillis: 60000
          testOnReturn: false
          maxActive: 20
          removeAbandoned: true
          removeAbandonedTimeout: 120
          logAbandoned: true